const CARD_DECK = [
  // Hearts
  { suit: "Hearts", rank: "Ace", value: 1 },
  { suit: "Hearts", rank: "2", value: 2 },
  { suit: "Hearts", rank: "3", value: 3 },
  { suit: "Hearts", rank: "4", value: 4 },
  { suit: "Hearts", rank: "5", value: 5 },
  { suit: "Hearts", rank: "6", value: 6 },
  { suit: "Hearts", rank: "7", value: 7 },
  { suit: "Hearts", rank: "8", value: 8 },
  { suit: "Hearts", rank: "9", value: 9 },
  { suit: "Hearts", rank: "10", value: 0 },
  { suit: "Hearts", rank: "Jack", value: 0 },
  { suit: "Hearts", rank: "Queen", value: 0 },
  { suit: "Hearts", rank: "King", value: 0 },
  // Diamonds
  { suit: "Diamonds", rank: "Ace", value: 1 },
  { suit: "Diamonds", rank: "2", value: 2 },
  { suit: "Diamonds", rank: "3", value: 3 },
  { suit: "Diamonds", rank: "4", value: 4 },
  { suit: "Diamonds", rank: "5", value: 5 },
  { suit: "Diamonds", rank: "6", value: 6 },
  { suit: "Diamonds", rank: "7", value: 7 },
  { suit: "Diamonds", rank: "8", value: 8 },
  { suit: "Diamonds", rank: "9", value: 9 },
  { suit: "Diamonds", rank: "10", value: 0 },
  { suit: "Diamonds", rank: "Jack", value: 0 },
  { suit: "Diamonds", rank: "Queen", value: 0 },
  { suit: "Diamonds", rank: "King", value: 0 },
  // Clubs
  { suit: "Clubs", rank: "Ace", value: 1 },
  { suit: "Clubs", rank: "2", value: 2 },
  { suit: "Clubs", rank: "3", value: 3 },
  { suit: "Clubs", rank: "4", value: 4 },
  { suit: "Clubs", rank: "5", value: 5 },
  { suit: "Clubs", rank: "6", value: 6 },
  { suit: "Clubs", rank: "7", value: 7 },
  { suit: "Clubs", rank: "8", value: 8 },
  { suit: "Clubs", rank: "9", value: 9 },
  { suit: "Clubs", rank: "10", value: 0 },
  { suit: "Clubs", rank: "Jack", value: 0 },
  { suit: "Clubs", rank: "Queen", value: 0 },
  { suit: "Clubs", rank: "King", value: 0 },
  // Spades
  { suit: "Spades", rank: "Ace", value: 1 },
  { suit: "Spades", rank: "2", value: 2 },
  { suit: "Spades", rank: "3", value: 3 },
  { suit: "Spades", rank: "4", value: 4 },
  { suit: "Spades", rank: "5", value: 5 },
  { suit: "Spades", rank: "6", value: 6 },
  { suit: "Spades", rank: "7", value: 7 },
  { suit: "Spades", rank: "8", value: 8 },
  { suit: "Spades", rank: "9", value: 9 },
  { suit: "Spades", rank: "10", value: 0 },
  { suit: "Spades", rank: "Jack", value: 0 },
  { suit: "Spades", rank: "Queen", value: 0 },
  { suit: "Spades", rank: "King", value: 0 },
];

module.exports = { CARD_DECK };
